version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /.github/**
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    labels: []
    groups:
      gha-minor:
        applies-to: version-updates
        update-types:
          - patch
          - minor
      gha-security:
        applies-to: security-updates
        update-types:
          - patch
          - minor
          - major

