version: 2


jobs:
  render:
    docker:
      - image: ojford/texlive:latest

    steps:
      - checkout

      - run:
          name: Acquire awesome-cv
          command: |
            apk add openssh git
            mkdir -p ~/.ssh
            echo -e 'Host github.com\n\tStrictHostKeyChecking no\n' >> ~/.ssh/config
            git submodule update --init --recursive

      - restore_cache:
          key: luatex-cache

      - run:
          name: Make CV
          command: |
            apk add make
            make cv.pdf

      - save_cache:
          key: luatex-cache
          paths:
            - /usr/local/texlive/texmf-var/luatex-cache

      - run:
          name: Collect artefacts
          command: |
            mkdir artefacts
            mv cv.log cv.pdf artefacts || true
          when: always

      - store_artifacts:
          path: artefacts

      - persist_to_workspace:
          root: .
          paths:
            - artefacts

workflows:
  version: 2

  workflow:
    jobs:
      - render
    
